### ISSUE TITLE
5.0.0 has an unspecified dependency on @oclif/config

### ISSUE THREAD

**Issue by mrzor** [oclif/cli-ux#65]
To fix, I've pinned my dep to 4.9.3 for the time being.

I see it specified as a devDependency. It could be that it was omitted to put it as an actual dependency, but maybe the correct resolution is subtler.

~~~~
zor@ ... $ npm start

> <snip>@1.0.0 start /Users/zor/<snip>
> node main.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '@oclif/config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/zor/<snip>/node_modules/@oclif/command/lib/command.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
~~~~

**Comment by localhostdotdev** [comment]
Still happening on 5.2.1

**Comment by yehudamakarov** [comment]
I see this is open for a while, but I may have a similar problem. Definitely the same error
